"""
Django settings for socialink project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from . import secrets
import dj_database_url
import io
import os
import environ
import google.auth
from google.cloud import secretmanager


# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# DEBUG = True

# env = environ.Env(
#     SECRET_KEY=(str, os.getenv("SECRET_KEY")),
#     DATABASE_URL=(str, os.getenv("DATABASE_URL")),
#     GS_BUCKET_NAME=(str, os.getenv("GS_BUCKET_NAME")),
# )

# # Attempt to load the Project ID into the environment, safely failing on error.
# try:
#     _, os.environ["GOOGLE_CLOUD_PROJECT"] = google.auth.default()
# except google.auth.exceptions.DefaultCredentialsError:
#     pass


# # Use local .env file in dev mode
# if os.getenv("PYTHON_ENV") == "dev":
#     print("Using local .env file")
#     DEBUG = True
# # Use GCP secret manager in prod mode
# elif os.getenv("GOOGLE_CLOUD_PROJECT", None):
#     project_id = os.getenv("GOOGLE_CLOUD_PROJECT")

#     client = secretmanager.SecretManagerServiceClient()
#     settings_name = os.getenv("SETTINGS_NAME", "django_app_settings")
#     name = f"projects/{project_id}/secrets/{settings_name}/versions/latest"
#     payload = client.access_secret_version(name=name).payload.data.decode(
#         "UTF-8"
#     )

#     env.read_env(io.StringIO(payload))
# else:
#     raise Exception(
#         "No local .env or GOOGLE_CLOUD_PROJECT detected. No secrets found."
#     )

# SECRET_KEY = env("SECRET_KEY")

# ALLOWED_HOSTS = ["*"]


# # Database
# # Use django-environ to parse the connection string
# DATABASES = {"default": env.db()}

# # If the flag as been set, configure to use proxy
# if os.getenv("USE_CLOUD_SQL_AUTH_PROXY", None):
#     DATABASES["default"]["HOST"] = "cloudsql-proxy"
#     DATABASES["default"]["PORT"] = 5432


# # Internationalization
# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_L10N = True

# USE_TZ = True


# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# GS_BUCKET_NAME = env("GS_BUCKET_NAME")
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
# STATICFILES_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
# GS_DEFAULT_ACL = "publicRead"

# Media files settings
# MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/images/'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

















# # Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mh-n2&$%8%023bklzla#h%5x&bprzp@x&3)#9s1r5g7)#l7cgj'

# # SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# #ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    'https://web-production-810a2.up.railway.app',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userauth.apps.UserauthConfig',
    'profile_management.apps.ProfileManagementConfig',
    'content_management.apps.ContentManagementConfig',
    'oauth_integration.apps.OauthIntegrationConfig',
    'sslserver',
    'csp',
    "storages"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

# # Allowed styles from Tailwind CSS CDN and own domain
# SECURE_CONTENT_TYPE_POLICY = "script-src 'self'; style-src 'self' https://unpkg.com/tailwindcss@^2; base-uri 'self'; form-action 'self'"

# Allowed styles from Tailwind CSS CDN and own domain
SECURE_CONTENT_TYPE_POLICY = (
    "script-src 'self' https://cdnjs.cloudflare.com; "
    "style-src 'self' https://cdn.tailwindcss.com; "
    "img-src 'self' data:; base-uri 'self'; form-action 'self'"
)
# Enable Report-Only mode
CSP_REPORT_ONLY = True  # Set to False for enforcement

# Define a secure endpoint for receiving reports
CSP_REPORT_URI = 'https://127.0.0.1:4000/report-csp-violation/'



ROOT_URLCONF = 'socialink.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'socialink.wsgi.application'


DATABASES = {
    'default': dj_database_url.parse('postgresql://postgres:ozsodeRWiakLaNGJWQaHqYTESHtmXwNm@junction.proxy.rlwy.net:52888/railway')
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': secrets.database_name,  # Replace with the name of your database
#         'USER': secrets.database_user,  # Replace with the database user
#         'PASSWORD': secrets.database_password,  # Replace with the database password
#         'HOST': secrets.database_host,  # Or the host where PostgreSQL is running
#         'PORT': secrets.database_port,  # Default PostgreSQL port
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'djangodevdb',
#         'USER': 'djangodevdbadmin',
#         'PASSWORD': '-;}tca#BGJM6=2/z',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',  # or the correct port if you've changed it
#     }
# }



PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# This tells Django where to collect static files (for production)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# This is optional: where your development static files live
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Media files (uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     BASE_DIR / 'static'
# ]

# MEDIA_URL = '/images/'
# MEDIA_ROOT = BASE_DIR / 'static/images'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
